宏观物理量可以分为两大类：
- 强度量
- 广延量

前者可以逐点地测量和改变，如温度、压力、电场强度、磁场强度等。
后者与物理系统的总质量有关，如体积、粒子总数、总能量、熵等（可以问物体的某一部分的粒子数，但不能问某一点处的粒子数）。

大多数广延量和强度量是成对出现的，如体积和压力、熵和温度。而每一对（称之为共轭变量）的乘积（点乘、内积），都具有能量的量纲。

一般说来，强度量是控制宏观系统发生相变的参数。

（铁磁相变、合金相变、液晶相变、超流超导等均跳过）

* 渗流相变
用尺寸相同的绝缘球和导电球堆成一个立方体。
如果导电球所占比例P够大，整个立方体当然会是一个导体。
如果导电球所占比例P太小，整个立方体一定不会完全导通。
P从0到1逐步增大的过程中，立方体上的通路是突然出现的。

仿照铁磁相变磁化强度描述，把临界点附近的成通概率写为：
- 成通概率 $\propto (P-P_{C})^{\beta}$
式中P从大于P_{C}的值接近P_{C}。
三维渗流相变中，\beta约为0.4~0.5。
而且，虽然P_{C}的值依赖于球的堆砌方式（面心立方堆砌、六角对称堆砌），但是\beta的值只与空间维数有关。

与其他相变类似的，P_{C}附近也有一些发散量，比如"有限"导电簇尺寸\xi。
\xi是P的函数，
- 当P很小时，\xi也不大；
- 当P接近P_{C}时，\xi迅速增大；
- 当P大于P_{C}时，去除完全连通的无穷大簇，剩下的自然越来越小。
\xi(P)在P_{C}附近发散，可以写成
- $\xi(P) \propto |P-P_{C}|^{-v}$
三维渗流相变中，v约为0.8~0.9。

小结：
- 相变普遍存在于自然界中。
- 引发相变的具体机制多种多样。
- 各种相变间的相似之处远超它们之间的差异。
- 相变理论的任务在于，透过个性，抓住共性。
      + 概括和说明那些最普遍、最本质的事情。

不同相变中，临界点附近的物理量奇异性非常相似。
现象的共性要求建立普遍的理论。
长期以来，人们用平均场理论来描述连续相变。

普朗克：一个好的分类已经是一种重要知识。

第K类相变：热力学势的第K阶导数开始出现不连续。
- 在自然界中，目前只看到了第一类、第二类相变。
      + 一类相变不是热力学奇异点，而只是两个相的函数交叉点。
      + 习惯上，二类以上的相变通称为连续相变或 *临界现象* 。
      + 二类相变热力学奇异点的奇异性质目前(92年)并不完全清楚。
- 波色-爱因斯坦凝聚理论上是第三类相变。

* 序参量
相变有什么共同特征？
首先是有序程度的改变，及与之相关的对称性（即某种不变性）变化。
许多相变都是从一种有序变化为另一种有序。

（上述渗流中，序参量应为导电概率。wang）

- 找出连续相变中的序参量，研究它的变化规律，是相变理论的首要任务。
- 序参量的结构很不一样，但在临界点上其绝对值连续地趋于0这一点相同。

序参量通常可以和一定的外场耦合，这些场称为"对偶场"。
序参量和对偶场是一对热力学共轭变量。

序参量结构额如何，临界点的数值是什么，这都是特殊性问题，必须针对具体的物理系统认真分析计算，没有捷径可循。
而一旦找到了在临界点处连续趋于0的序参量，以后的描述就是普遍的了（如下所述）。

* 布朗理论
1937年郎道提出的平均场理论是非常通用的。
在临界点附近展开热力学势，并分析稳定性。
- \Gamma(M) = \Gamma_{0}(T) + a(T)M^{2}/2 + b(T)M^{4}/4 + ...

平均场论的基本假定有两条：
- 热力学势在相变点附近是序参量的解析函数，且可以按上式展开；
- 展开系数a(T)在T_{C}点变号，而b(T)是正的。
有了这两条假定，就可以推得一系列结论，并与实验比较。

奥尔恩斯坦等认为，在临界点附近的随机涨落不再互相独立，
他们提出，即使分子间是短程作用，也可能出现长程的关联。

物理参数的无穷小变化引起的对称破缺（对称性突然降低），
这是 *连续相变的本质* 。
